nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/diamondlightsource/graph-energy-scan
  pullPolicy: Always
  tag: ""

imagePullSecrets: []

database:
  host: mysql+pymysql://ispyb-mariadb-galera-headless/ispyb
  user: ispyb_ro

replicaCount: 1

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
