nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/diamondlightsource/graph-energy-scan
  pullPolicy: Always
  tag: ""

imagePullSecrets: []

otelCollectorUrl: http://federation-opentelemetry-collector:4317

database:
  host: mysql+aiomysql://ispyb-mariadb-galera-headless/ispyb
  user: ispyb_ro

replicaCount: 1

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
                - ispyb
            - key: app.kubernetes.io/name
              operator: In
              values:
                - mariadb-galera
        topologyKey: kubernetes.io/hostname
