on:
  workflow_call:
    inputs:
      tox:
        type: string
        description: What to run under tox
        required: true


jobs:
  run:
    runs-on: "ubuntu-latest"
    services:
      ispyb:
        image: ghcr.io/diamondlightsource/ispyb-database:v3.0.0
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: rootpassword
        options: >
          --health-cmd "/usr/local/bin/healthcheck.sh --defaults-file=/ispyb/.my.cnf --connect"
    env:
      DATABASE_URL: mysql+aiomysql://root:rootpassword@localhost/ispyb_build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python packages
        uses: ./.github/actions/install_requirements

      - name: Run tox
        run: tox -e ${{ inputs.tox }}
