name: CI

on:
  push:
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  lint:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/_tox.yml
    with:
      tox: pre-commit,type-checking

  test:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    strategy:
      matrix:
        python-version: ["3.11", "dev"]
      fail-fast: false
    uses: ./.github/workflows/_test.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  container:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/_container.yml
    permissions:
      contents: read
      packages: write

  dist:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/_dist.yml
  
  release:
    if: github.ref_type == 'tag'
    needs: [dist]
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
